sudo: false

language: node_js
node_js:
 - '0.10'
 - '0.12'
 - iojs

script:
  - cp userdata/userdata.json.example userdata/userdata.json
  - npm run newkey
  - ./node_modules/grunt-crx/node_modules/.bin/crx keygen
  - npm run build